"""create countries table

Revision ID: a80646bce391
Revises: 5f5557cd732c
Create Date: 2025-10-31 16:45:21.907047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80646bce391'
down_revision: Union[str, Sequence[str], None] = '5f5557cd732c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capital', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('estimated_gdp', sa.Float(), nullable=True),
    sa.Column('flag_url', sa.String(length=500), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
